load("//java:junit5.bzl", "junit5_test_library")

package(
    default_testonly = 1,
    default_visibility = ["//visibility:public"],
)

junit5_test_library(
    name = "annotations",
    srcs = [
        "EnormousTest.java",
        "LargeTest.java",
        "MediumTest.java",
        "SmallTest.java",
    ],
)
